-- MySQL Script generated by MySQL Workbench
-- Fri 18 May 2018 02:05:13 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bifi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bifi` ;

-- -----------------------------------------------------
-- Schema bifi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bifi` DEFAULT CHARACTER SET utf8 ;
USE `bifi` ;

-- -----------------------------------------------------
-- Table `bifi`.`Klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bifi`.`Klant` ;

CREATE TABLE IF NOT EXISTS `bifi`.`Klant` (
  `KlantID` INT NOT NULL,
  `Bedrijfsnaam` VARCHAR(100) NULL,
  `Rechtsvorm` CHAR(10) NULL,
  `VAT` VARCHAR(14) NULL,
  `BankRek` VARCHAR(34) NULL,
  `Giro` VARCHAR(7) NULL,
  `Bik` VARCHAR(11) NULL,
  PRIMARY KEY (`KlantID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bifi`.`Persoon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bifi`.`Persoon` ;

CREATE TABLE IF NOT EXISTS `bifi`.`Persoon` (
  `PersoonID` INT NOT NULL,
  `Voornaam` VARCHAR(20) NULL,
  `Tussenvoegsel` CHAR(10) NULL,
  `Achternaam` VARCHAR(100) NULL,
  `Telefoon` INT(20) NULL,
  `Fax` VARCHAR(200) NULL,
  `Geslacht` VARCHAR(1) NULL,
  `KlantID` INT NOT NULL,
  PRIMARY KEY (`PersoonID`),
  INDEX `fk_Persoon_Klant_idx` (`KlantID` ASC),
  CONSTRAINT `fk_Persoon_Klant`
    FOREIGN KEY (`KlantID`)
    REFERENCES `bifi`.`Klant` (`KlantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bifi`.`Adres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bifi`.`Adres` ;

CREATE TABLE IF NOT EXISTS `bifi`.`Adres` (
  `AdresID` INT NOT NULL,
  `Straat` CHAR(60) NULL,
  `Type` CHAR(1) NULL,
  `Huisnummer` CHAR(10) NULL,
  `postcode` CHAR(6) NULL,
  `Plaats` CHAR(20) NULL,
  `BIC` CHAR(10) NULL,
  `KlantID` INT NOT NULL,
  PRIMARY KEY (`AdresID`),
  INDEX `fk_Adressen_Klant1_idx` (`KlantID` ASC),
  CONSTRAINT `fk_Adressen_Klant1`
    FOREIGN KEY (`KlantID`)
    REFERENCES `bifi`.`Klant` (`KlantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
